# Generated by Django 5.2.4 on 2025-07-09 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_remove_course_name_course_course_id_course_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=20)),
                ('course_id', models.CharField(max_length=100)),
                ('progress', models.IntegerField(default=0)),
                ('status', models.CharField(default='Not Completed', max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='grade',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='employee',
            name='practice',
            field=models.CharField(max_length=100),
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='course',
            name='title',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='emp_id',
        ),
        migrations.AddField(
            model_name='course',
            name='course_name',
            field=models.CharField(default='Unknown Course', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(default='TEMP123', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='course_id',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='CourseProgress',
        ),
        migrations.DeleteModel(
            name='Grade',
        ),
        migrations.DeleteModel(
            name='Practice',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
